---
title: "Titanic Association Rule"
output: html_notebook
---

# The Titanic Dataset

The Titanic dataset is used in this example, which can be downloaded as "titanic.raw.rdata" at the Data page.

```{r}
str(titanic.raw)
```

## Association Rule Mining
```{r}
library(arules)
# find association rules with default settings
rules <- apriori(titanic.raw)
inspect(rules)
```

## Survived=No, Survived=Yes

We then set rhs=c("Survived=No", "Survived=Yes") in appearance to make sure that only "Survived=No" and "Survived=Yes" will appear in the rhs of rules.

```{r}
rules <- apriori(titanic.raw,
                 parameter = list(minlen=2, supp=0.005,
                                  conf=0.8),
                 appearance = list(rhs=c("Survived=No", "Survived=Yes"),
                                   default="lhs"),
                 control = list(verbose=F))
rules.sorted <- sort(rules, by="lift")
inspect(rules.sorted)
```

## Prune Rules

```{r}
# find redundant rules
subset.matrix <- is.subset(rules.sorted, rules.sorted)
subset.matrix[lower.tri(subset.matrix, diag=T)] <- NA
redundant <- colSums(subset.matrix, na.rm=T) >= 1
which(redundant)
# remove redundant rules
rules.pruned <- rules.sorted[!redundant]
inspect(rules.pruned)
```

## Visualize Rules

```{r}
library(arulesViz)
plot(rules)
```

```{r}
plot(rules, method="graph", control=list(type="items"))
```

```{r}
plot(rules, method="paracoord", control=list(reorder=TRUE))
```